version: "3"

services:
  web:
    build: .
    tty: true
    volumes:
      - ".:/app"
    ports:
      - "80:80"
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=password"
